AllCops:
  Include:
    - 'app/**/*.rb'
    - 'config/**/*.rb'
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
  Exclude:
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'db/*.rb'
    - 'bin/**/*'
    - 'public/uploads/**/*'

  Rails:
    Enabled: true
  DisplayCopNames: true
  StyleGuideCopsOnly: true
  Lint/UselessAssignment:
    Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15
