# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 056c99b4d894e34ad72ecb970e27e56032e4d11e94e6159dfb65abda5827c3dbd1d7c78569d2c573aff6ae0ce06da9a6f1ddef8303f8c512a244592c9a56d66e
  facebook_app_id: 893379254091974
  fecebook_app_secret: 792ff7a235b9165114476a3f5ef75ccf
  vkontakte_app_id: 5168337
  vkontakte_app_secret: k3LExpKNUtxH0W1cIWrW
  twitter_app_id: RPguPOUChRvLEQjdgDbgwPLwA
  twitter_app_secret: kqhS28CdW9u0Vg8JzIJ5Vo8mybQI940Qq1rnookVM4dUeJovuP

test:
  secret_key_base: e3f194c8e0fa3d26941af6e0be0abf72e7ff4402b99d9df0aa540197aa29a7a59fb904e71551e1c223e3a665ca9f5e19f42c7faef09b2a0660e6d99d32141481

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  fecebook_app_secret: <%= ENV["FECEBOOK_APP_SECRET"] %>
  vkontakte_app_id: <%= ENV["VKONTAKTE_APP_ID"] %>
  vkontakte_app_secret: <%= ENV["VKONTAKTE_APP_SECRET"] %>
  twitter_app_id: <%= ENV["TWITTER_APP_ID"] %>
  twitter_app_secret: <%= ENV["TWITTER_APP_SECRET"] %>
